steps:
  - name: ":package: Prepare gems and database"
    env:
      RAILS_ENV: "test"
    command:
      - "bundle install"
      - "rake db:create"
      - "rake db:migrate"
    timeout_in_minutes: 10

  - wait

  - name: ":rubocop: Lint Ruby syntax"
    command:
      - "rubocop"
    timeout_in_minutes: 10

  - wait

  - name: ":ruby: Test Rails API"
    command:
      - "rails test"
    timeout_in_minutes: 10

  - wait

  - name: ":rocket: Deploy to production server"
    command:
      - "mina deploy"
    timeout_in_minutes: 10
    branches: "production"
