name: Continuous Deployment

on:
  push:
    branches:
      - 'production'

jobs:
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   services:
  #     postgres:
  #       image: postgres:11
  #       ports: ["5432:5432"]
  #       env:
  #         POSTGRES_USER: bot
  #         POSTGRES_DB: interflux_test
  #         POSTGRES_PASSWORD: password
  #   env:
  #     RAILS_ENV: test
  #     PG_HOST: localhost
  #     PG_USER: bot
  #     PG_DATABASE: interflux_test
  #     PG_PASSWORD: password
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         bundler-cache: true
  #     - run: bin/rails db:create
  #     - run: bin/rails db:schema:load
  #     - run: bin/rails test --verbose

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # needs: test
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      DOMAIN: api.interflux.com
      URL: bot@api.interflux.com
    steps:
      - uses: actions/checkout@v2
      - run: echo "REVISION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - run: mkdir ~/.ssh
      - run: 'echo "$PRIVATE_KEY" > ~/.ssh/$URL'
      - run: 'echo "IdentityFile ~/.ssh/$URL" > ~/.ssh/config'
      - run: ssh-keyscan -H $DOMAIN > ~/.ssh/known_hosts
      - run: chmod 0755 ~/.ssh/
      - run: chmod 600 ~/.ssh/$URL
      - run: chmod 644 ~/.ssh/known_hosts
      - run: remote/deploy.sh
      - run: ssh $URL "cd /var/www/$DOMAIN/builds/production/$REVISION; ls -la; bin/rails db:migrate"
      # - run: ssh -i ~/.ssh/$USER@$DOMAIN $USER@$DOMAIN "cd /var/www/$DOMAIN; bin/rails db:migrate"
      # - name: Sanity check
      #   run: 'curl --unix-socket /var/www/api.interflux.com/sockets/puma.sock http://localhost/sanity-check -H "Content-Type: application/vnd.api+json"'
