name: Continuous Deployment

on:
  push:
    branches:
      - 'production'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: bot
          POSTGRES_DB: interflux_test
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      PG_HOST: localhost
      PG_USER: bot
      PG_DATABASE: interflux_test
      PG_PASSWORD: password
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/rails db:create
      - run: bin/rails db:schema:load
      - run: bin/rails test --verbose

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    env:
      PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
    steps:
      - uses: actions/checkout@v2
      - run: mkdir ~/.ssh
      - run: 'echo "$PRIVATE_KEY" > ~/.ssh/bot@server.interflux.com'
      - run: ssh-keyscan -H server.interflux.com > ~/.ssh/known_hosts
      - run: chmod 0755 ~/.ssh/
      - run: chmod 600 ~/.ssh/bot@server.interflux.com
      - run: chmod 644 ~/.ssh/known_hosts
      # - run: remote/deploy.sh
