name: Continuous Integration

on:
  push:
    branches:
      - '**'
      - '!production'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: interflux
          POSTGRES_DB: interflux_test
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v2
      # - run: sudo apt-get -yqq install libpq-dev
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup test database
        env:
          RAILS_ENV: test
          PG_HOST: localhost
          PG_USER: postgres
          PG_DATABASE: postgres
          PG_PASSWORD: password
        run: bin/rails db:setup
      # - run: gem install bundler
      # - run: gem install rails
      # - run: bin/bundle install --jobs 4 --retry 3
      # - run: bin/rails db:environment:set RAILS_ENV=test
      # - run: bin/rails db:create
      # - run: bin/rails db:migrate
      - run: bin/rails test --verbose
